[window]
opacity = 0.7
dimensions = {columns = 135, lines = 30}

[font]
size = 12

[keyboard]
bindings = [
{key = "T", mods = "Control|Shift", action = "SpawnNewInstance"},
{key = "T", mods = "Super|Shift", action = "SpawnNewInstance"},
]
