[shell]
program = "zellij"

[window]
opacity = 0.7

[font]
size = 12

[keyboard]
bindings = [
{key = "T", mods = "Control|Shift", action = "SpawnNewInstance"},
{key = "T", mods = "Super|Shift", action = "SpawnNewInstance"},
]
